-- Code for creating each table in the database
-- This includes the code for specifying the check constraints for each table
-- This includes the code for specifying the storage engine for each table